# Generated by Django 5.2.9 on 2025-12-03 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        ("platforms", "0002_alter_platform_created_by_alter_platform_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to="platforms.userplatform",
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to="platforms.userplatform",
                verbose_name="Actualizado por",
            ),
        ),
    ]
