# Generated by Django 5.2.9 on 2025-12-03 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platforms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to="platforms.userplatform",
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to="platforms.userplatform",
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="userplatform",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to="platforms.userplatform",
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="userplatform",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to="platforms.userplatform",
                verbose_name="Actualizado por",
            ),
        ),
    ]
